### ISSUE TITLE
Generate code snippets for examples in conceptual articles

### ISSUE THREAD

**Issue by maisarissi** [OneDrive/apidoctor#123] opened 2022-04-05 14:07 UTC
Related to https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/880

The content below was mentioned in this [comment](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/880#issuecomment-1088331055) by @andrueastman :

> It looks like this page is a conceptual doc and has code snippets generated.
> 
> https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings?tabs=http
> 
> This shows that APIDoctor does indeed scan and pick http examples from conceptual articles but for some reason some other conceptual pages are not picked up.
> 
> This could be potentially due to either different formatting across the conceptual docs pages causing APIDoctor not to pick up the examples or a bug (or feature? 😅 ) in APIDoctor that makes the other pages get skipped.
> This would need some investigation to get to the cause.

**Comment by FaithOmbongi** [comment] 2022-06-13 06:51
Hi @maisarissi - Any update on the root cause of the problem?

**Comment by maisarissi** [comment] 2022-06-24 13:58
Hi @FaithOmbongi . I don't have any updates on this. @ddyett how can help us with the investigation?

**Comment by FaithOmbongi** [comment] 2022-09-12 13:10
Hi @maisarissi, any update resolving this issue?

**Closed** 2022-10-03 07:57 UTC
